server:
  port: 7000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  packagesToScan: com.runapp.achievementservice

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
#  внимание
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/AchievementService
    username: postgres
    password: 25032001
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create-drop
#      внимание
    defer-datasource-initialization: true
  application:
    name: workout-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 6MB
  cloud:
    openfeign:
      client:
        config:
          storage-service:
            url: http://localhost:6500
          achievement-service:
            url: http://localhost:3333
          profile-service:
            url: http://localhost:4000
          guild-service:
            url: http://localhost:8000
          shoes-service:
            url: http://localhost:2222

storage-directory: WorkoutService/


